adsprpc: map the persist buffer outside the mutex
qualcomm/fastrpc pull request #82
Opened 2024-10-15 11:38 UTC by quic-psaddam

Currently, allocation and mapping of buffer is happening inside mutex.If mapping on one session gets stuck on DSP,other sessions will not be able to acquire the mutex and will get hung while getting spawned. Map the buffer outside the mutex.

2024-10-17 06:42 UTC, ekanshibu commented on src/fastrpc_log.c
> +     locked = false;
indentation

2024-10-30 11:23 UTC, quic-mtharu commented on src/fastrpc_apps_user.c
> +  fastrpc_log_init(domain, dsppd);
Could you provide details about the variable being passed in this function? Is it a global variable, or might its declaration be missing?

2024-10-30 11:31 UTC, quic-mtharu commented on src/fastrpc_log.c
> +    pthread_mutex_lock(&persist_buf.mut);
Could you please add error handling for the pthread_mutex_lock(mut) failure case? It’s important to ensure that the function gracefully handles any potential locking failures to maintain robustness.

2024-11-06 15:39 UTC, quic-mtharu requested changes
[src/fastrpc_apps_user.c](https://github.com/quic/fastrpc/pull/82/files#diff-4effcf8d7496aca0812640a491f8b5abfed1f349f95b552acf2d1775c192a480):3950 dsppd declaration missing

2025-01-08 10:44 UTC, quic-psaddam commented on src/fastrpc_log.c
> +    pthread_mutex_lock(&persist_buf.mut);
we are handing code gracefully when pthread_mutex_lock fails.

2025-07-28 02:15 UTC, closed without merging